# Secret להגנה על API_KEY
apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
type: Opaque
data:
  API_KEY: VjVYSlRGVURVUzc2UENCUEM0OVk4SktRMw==


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-weather-app
  template:
    metadata:
      labels:
        app: my-weather-app
    spec:
      serviceAccountName: ecr-access-sa  # הוספת Service Account
      containers:
        - name: my-weather-app
          image: 897729114707.dkr.ecr.eu-central-1.amazonaws.com/my-weather-app:1.0.37  # התמונה מ-ECR
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: API_KEY
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
